// TODO Implement this library.
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAX1Rb6nZivBSOF1Y2JnKVZA5zAUJw6c',
    appId: '1:778921494224:android:7c01b36ae02b832d3c00d5',
    messagingSenderId: '778921494224',
    projectId: 'todoflutter-f6f15',
    storageBucket: 'todoflutter-f6f15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7sUnBhshS8_am0giKcdljigFF9jOGAU',
    appId: '1:778921494224:ios:2dd45346bb1c31833c00d5',
    messagingSenderId: '778921494224',
    projectId: 'todoflutter-f6f15',
    storageBucket: 'todoflutter-f6f15.appspot.com',
    iosClientId: '778921494224-0td9bufevarnf14gucokctinnfr3b53f.apps.googleusercontent.com',
    iosBundleId: 'com.example.asana',
  );
}